-- ASSESSMENT_REQUIREMENT definition

  CREATE TABLE "ASSESSMENT_REQUIREMENT" 
   (	"ASSESSMENT_REQUIREMENT_ID" RAW(16) DEFAULT SYS_GUID(), 
	"ASSESSMENT_CODE" VARCHAR2(7) NOT NULL ENABLE,
	"ASSESSMENT_REQUIREMENT_CODE" VARCHAR2(4) NOT NULL ENABLE,
	"CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
	"CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
	"UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "ASSESSMENT_REQUIREMENT_PK" PRIMARY KEY ("ASSESSMENT_REQUIREMENT_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE, 
	 CONSTRAINT "ASSESSMENT_REQUIREMENT_FK1" FOREIGN KEY ("ASSESSMENT_REQUIREMENT_CODE")
	  REFERENCES "ASSESSMENT_REQUIREMENT_CODE" ("ASSESSMENT_REQUIREMENT_CODE") ENABLE, 
	 CONSTRAINT "FK_ASSESSMENT_CODE" FOREIGN KEY ("ASSESSMENT_CODE")
	  REFERENCES "ASSESSMENT_CODE" ("ASSESSMENT_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA" NO INMEMORY ;