GRANT SELECT ON ASSESSMENT_CODE TO GRAD_READONLY;
GRANT SELECT ON ASSESSMENT_REQUIREMENT_CODE TO GRAD_READONLY;
GRANT SELECT ON ASSESSMENT_REQUIREMENT TO GRAD_READONLY;
GRANT SELECT ON FLYWAY_SCHEMA_HISTORY TO GRAD_READONLY;
