ALTER TABLE ASSESSMENT_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE ASSESSMENT_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE ASSESSMENT_REQUIREMENT_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE ASSESSMENT_REQUIREMENT_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE ASSESSMENT_REQUIREMENT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE ASSESSMENT_REQUIREMENT
    MODIFY UPDATE_USER VARCHAR2(100);





