GRANT SELECT ON ASSESSMENT_CODE TO GRAD_READONLY;
GRANT SELECT ON ASSESSMENT_REQUIREMENT_CODE TO GRAD_READONLY;
GRANT SELECT ON ASSESSMENT_REQUIREMENT TO GRAD_READONLY;
GRANT SELECT ON TRAX_STUDENT_ASSESSMENTS TO GRAD_READONLY;