---
apiVersion: v1
kind: Template
labels:
  template: 'educ-grad-assessment-api-template'
metadata:
  name: 'educ-grad-assessment-api-template'
objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      labels:
        build: educ-grad-assessment-api
      name: educ-grad-assessment-api-bc
      namespace: 77c02f-tools
    spec:
      resources: 
        requests: 
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
      source:
        git:
          ref: develop/km
          uri: 'https://github.com/bcgov/${REPO_NAME}'
        type: Git
      strategy:
        dockerStrategy:
          type: Docker
          pullSecret:
            name: artifactory-creds
      output:
        to:
          kind: ImageStreamTag
          name: 'educ-grad-assessment-api:latest'
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: educ-grad-assessment-api
      namespace: 77c02f-tools
      labels:
        build: educ-grad-assessment-api
    spec:
      lookupPolicy:
        local: false
parameters:
  - description: Name of the Git Repository
    displayName: REPO_NAME
    name: REPO_NAME
    required: true