---
apiVersion: v1
kind: Template
labels:
  template: 'educ-grad-assessment-api-template'
metadata:
  name: 'educ-grad-assessment-api-template'
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: educ-grad-assessment-api
      name: educ-grad-assessment-api-bc
      namespace: 77c02f-tools
    spec:
      resources: 
        requests: 
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1500m
          memory: 3Gi
      source:
        git:
          ref: develop/km
          uri: 'https://github.com/bcgov/EDUC-GRAD-ASSESSMENT-API'
        type: Git
      strategy:
        dockerStrategy:
          type: Docker
          pullSecret:
            name: artifactory-creds
      output:
        to:
          kind: ImageStreamTag
          name: 'educ-grad-assessment-api-main:latest'
